[package]
name = "unrolled-exponential-linked-list"
version = "0.1.0"
authors = ["Kerollmops <clement@meilisearch.com>"]
edition = "2018"

[dependencies]
# Optional support for bumpalo
bumpalo = { version = "3.5.0", optional = true }

[features]
nightly = []
